version: '3'
services:
  postgres:
    image: postgres:9.5
    environment:
      - "POSTGRES_USER=tove"
      - "POSTGRES_PASSWORD=tove"
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RAILS_ENV: development
    volumes:
      - ./:/app
      - gem_cache:/usr/local/bundle
    ports:
      - "3000:80"
    environment:
      - "RAILS_ENV=development"
      - "DATABASE_URL=postgresql://tove:tove@postgres/tove_development"
      - "DATABASE_URL_TEST=postgresql://tove:tove@postgres/tove_test"
    links:
      - postgres:postgres

volumes:
  gem_cache: