name: Production DB Migration

on:
  workflow_dispatch:

jobs:
  db_migration_production:
    name: Production DB Migration
    uses: zooniverse/ci-cd/.github/workflows/db_migration.yaml@main
    with:
      app_name: tove
      environment: production
    secrets:
      creds: ${{ secrets.AZURE_AKS }}

  slack_notification:
    name: Slack notification
    uses: zooniverse/ci-cd/.github/workflows/slack_notification.yaml@main
    needs: db_migration_production
    if: always()
    with:
      commit_id: ${{ github.sha }}
      job_name: Production DB Migration / db_migration_production
      status: ${{ needs.db_migration_production.result }}
      title: "Tove Production database migration complete"
      title_link: "https://alice.zooniverse.org"
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
