name: Deploy to Production

on:
  push:
    tags:
      - production-release
  workflow_dispatch:

jobs:
  deploy_production:
    name: Deploy to Production
    uses: zooniverse/tove/.github/workflows/deploy_app.yaml@production-release
    with:
      commit_id: ${{ github.sha }}
      environment: production
    secrets:
      creds: ${{ secrets.AZURE_AKS }}
  slack_notification:
    name: Slack notification
    uses: zooniverse/ci-cd/.github/workflows/slack_notification.yaml@main
    needs: deploy_production
    if: always()
    with:
      commit_id: ${{ github.sha }}
      job_name: Deploy to Production / deploy_app
      status: ${{ needs.deploy_production.result }}
      title: "Tove Production deploy complete"
      title_link: "https://alice.zooniverse.org"
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
