name: ZooniCI

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build and Push to GH CR
    steps:
    - name: Obtain Latest Git ONLY within container for checkout
      run: |
        apt-get update
        apt-get install -y git
    - name: Checkout repo to get .git folder
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: zooniverse/tove:${{ github.sha }}

    # Preview of Kubernetes deployment
    # # Set the target AKS cluster.
    # - uses: Azure/aks-set-context@v1
    #   with:
    #     creds: '${{ secrets.AZURE_AKS }}'
    #     cluster-name: microservices
    #     resource-group: kubernetes

    # - uses: Azure/k8s-deploy@v1.4
    #   with:
    #     manifests: |
    #       manifests/deployment.yml
    #       manifests/service.yml
    #     images: |
    #       demo.azurecr.io/k8sdemo:${{ github.sha }}
