name: Deploy to Staging

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_push_image:
    name: Build and Push Image
    uses: zooniverse/ci-cd/.github/workflows/build_and_push_image.yaml@main
    with:
      repo_name: tove
      commit_id: ${{ github.sha }}
      latest: true

  db_migration_staging:
    name: Staging DB Migration
    uses: zooniverse/ci-cd/.github/workflows/db_migration.yaml@main
    needs: build_and_push_image
    with:
      app_name: tove
      environment: staging
      commit_id: ${{ github.sha }}
    secrets:
      creds: ${{ secrets.AZURE_AKS }}

  deploy_staging:
    name: Deploy to Staging
    uses: zooniverse/ci-cd/.github/workflows/deploy_app.yaml@main
    needs: [build_and_push_image, db_migration_staging]
    with:
      app_name: tove
      repo_name: tove
      commit_id: ${{ github.sha }}
      environment: staging
    secrets:
      creds: ${{ secrets.AZURE_AKS }}

  deploy_slack_notification:
    name: Slack notification
    uses: zooniverse/ci-cd/.github/workflows/slack_notification.yaml@main
    needs: db_migration_staging
    if: always()
    with:
      commit_id: ${{ github.sha }}
      job_name: Deploy to Staging / deploy_app
      status: ${{ needs.deploy_staging.result }}
      title: "Tove Staging deploy complete"
      title_link: "https://alice.preview.zooniverse.org"
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

  migration_slack_notification:
    name: Slack notification
    uses: zooniverse/ci-cd/.github/workflows/slack_notification.yaml@main
    needs: db_migration_staging
    if: always()
    with:
      commit_id: ${{ github.sha }}
      job_name: Staging DB Migration / db_migration_staging
      status: ${{ needs.db_migration_staging.result }}
      title: "Tove Staging database migration complete"
      title_link: "https://alice.preview.zooniverse.org"
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
