name: Deploy to Staging

on:
  push:
      branches:
        - master
  workflow_dispatch:

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get current deploy
      run: |
        echo "DEPLOYED_IMAGE_TAG=$(kubectl get deployment tove-staging-app -o=jsonpath='{$.spec.template.spec.containers[:1].image}' | cut -d':' -f 2)" >> $GITHUB_ENV

    - name: Check if deploy is necessary
      run: |
        if [ $DEPLOYED_IMAGE_TAG == ${{ github.sha }} ]; then
          echo "::warning::Deployed image matches latest commit, no new code to deploy. "
          exit 0
        fi

    - name: Create commit.txt
      run: |
        echo ${{ github.sha }} > commit_id.txt

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ghcr.io/zooniverse/tove:${{ github.sha }}
          ghcr.io/zooniverse/tove:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Set the target AKS cluster
      uses: Azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_AKS }}'
        cluster-name: microservices
        resource-group: kubernetes

    - name: Modify & apply template
      run: |
        sed "s/__IMAGE_TAG__/${{ github.sha }}/g" ./kubernetes/deployment-staging.tmpl \
          | kubectl apply -f -

    - name: Slack notification
      uses: 8398a7/action-slack@v3
      if: always()
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        fields: took
        status: custom
        custom_payload: |
          {
            "channel": "#deploys",
            "icon_emoji": ":octocat:",
            "username": "Deploy Action",
            "attachments": [{
              "color": '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
              "mrkdwn_in": ["text"],
              "author_name": "${{ github.actor }}",
              "author_link": "https://github.com/${{ github.actor }}/",
              "author_icon": "https://github.com/${{ github.actor }}.png?size=40",
              "title": "Tove Staging deploy complete",
              "title_link": "https://alice.preview.zooniverse.org",
              "fields": [
                  {
                      "title": "Status",
                      "value": '${{ job.status }}' === 'success' ? `:white_check_mark: Success in ${process.env.AS_TOOK}` : '${{ job.status }}' === 'failure' ? ':x: Failed' : ':warning: Warning',
                      "short": true
                  },
                  {
                      "title": "Triggered by",
                      "value": "${{ github.event_name }}",
                      "short": true
                  },
                  {
                      "title": "Initiated by",
                      "value": "<https://github.com/${{ github.repository }}/pull/${{ github.event.number }}|${{ github.event.pull_request.title }}>"
                  },
                  {
                      "title": "Run Link",
                      "value": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }
              ],
              "thumb_url": "https://raw.githubusercontent.com/zooniverse/Brand/master/style%20guide/logos/zooniverse-emblem/zooniverse-logo-teal.png",
              "footer": "<https://github.com/${{ github.repository }}|${{ github.repository }}> #${{ github.run_number }}",
              "footer_icon": "https://www.zooniverse.org/favicon.ico"
            }]
          }
