name: Deploy to Staging

on:
  workflow_dispatch:

jobs:
  deploy-to-staging:
    runs-on: ubuntu-latest
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Create commit.txt
      run: |
        echo ${{ github.sha }} > commit_id.txt

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          ghcr.io/zooniverse/tove:${{ github.sha }}
          ghcr.io/zooniverse/tove:latest

    - name: Set the target AKS cluster
    - uses: Azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_AKS }}'
        cluster-name: microservices
        resource-group: kubernetes

    # Not yet
    # - name: Apply templates to AKS cluster
    # - uses: Azure/k8s-deploy@v1.4
    #   with:
    #     manifests: kubernetes/deployment-staging.yml
    #     images: ghcr.io/zooniverse/tove:${{ github.sha }}
