name: Run Rake Task

on:
  workflow_dispatch:
    inputs:
      rake_task:
        description: Rake task to run
        required: true
        default: 'routes'

jobs:
  run_rake_task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set the target AKS cluster
        uses: Azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_AKS }}'
          cluster-name: microservices
          resource-group: kubernetes

      - name: Set environment variables
        run: |
          echo "DEPLOYED_IMAGE_TAG=$(kubectl get deployment tove-staging-app -o=jsonpath='{$.spec.template.spec.containers[:1].image}' | cut -d':' -f 2)" >> $GITHUB_ENV
          echo "JOB_NAME=tove-rake-task-staging-${{ github.run_number }}" >> $GITHUB_ENV

      - name: Modify & apply template
        run: |
          sed "s/__IMAGE_TAG__/$DEPLOYED_IMAGE_TAG/g" ./kubernetes/job-rake-task-staging.tmpl \
            | sed "s/__JOB_NAME__/$JOB_NAME/g" \
            | sed "s/__RAKE_TASK_NAME__/${{ github.event.inputs.rake_task }}/g" \
            | kubectl apply -f -

      - name: Wait for completion or failure
        run: |
          kubectl wait --for=condition=complete job/$JOB_NAME & completion_pid=$!
          kubectl wait --for=condition=failed job/$JOB_NAME && exit 1 & failure_pid=$!
          wait -n $completion_pid $failure_pid
          exit_code=$?
          echo "JOB_EXIT_CODE=$exit_code" >> $GITHUB_ENV
          exit $exit_code

      - name: Log output
        if: always()
        run: |
          kubectl describe job/$JOB_NAME
          kubectl logs $(kubectl get pods --selector=job-name=$JOB_NAME --output=jsonpath='{.items[*].metadata.name}')

      - name: Clean up job if successful
        if: always()
        run: |
          if [ $JOB_EXIT_CODE -eq 0 ]
          then
            kubectl delete job $JOB_NAME
          fi
