name: Send Slack notification

on:
  # Run this workflow from other workflows
  workflow_call:
    inputs:
      commit_id:
        description: 'HEAD commit hash'
        required: true
        type: string
      job_name:
        description: 'Job name to report on'
        required: true
        type: string
      status:
        description: 'Job status'
        required: true
        type: string
      title:
        description: 'Notification title'
        required: true
        type: string
      title_link:
        description: 'Notification title link'
        required: true
        type: string
    secrets:
      slack_webhook_url:
        required: true

jobs:
  slack_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Get associated PR info
        run: |
          response=$(curl https://api.github.com/repos/zooniverse/tove/commits/${{ inputs.commit_id }}/pulls)
          echo "PR_URL=$(jq -r '.[].html_url' <<< "${response}")" >> $GITHUB_ENV
          echo "PR_TITLE=$(jq -r '.[].title' <<< "${response}")" >> $GITHUB_ENV

      - name: Slack notification
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_url }}
        with:
          job_name: ${{ inputs.job_name }}
          fields: took
          status: custom
          custom_payload: |
            {
              "channel": "#deploys",
              "icon_emoji": ":octocat:",
              "username": "Deploy Action",
              "attachments": [{
                "color": '${{ inputs.status }}' === 'success' ? 'good' : '${{ inputs.status }}' === 'failure' ? 'danger' : 'warning',
                "mrkdwn_in": ["text"],
                "author_name": "${{ github.actor }}",
                "author_link": "https://github.com/${{ github.actor }}/",
                "author_icon": "https://github.com/${{ github.actor }}.png?size=40",
                "title": "${{ inputs.title }}",
                "title_link": "${{ inputs.title_link }}",
                "fields": [
                    {
                        "title": "Status",
                        "value": '${{ inputs.status }}' === 'success' ? `:white_check_mark: Success in ${process.env.AS_TOOK}` : '${{ inputs.status }}' === 'failure' ? ':x: Failed' : ':warning: Warning',
                        "short": true
                    },
                    {
                        "title": "Triggered by",
                        "value": "${{ github.event_name }}",
                        "short": true
                    },
                    {
                      "title": "Initiated by",
                      "value": "<${{ env.PR_URL }}|${{ env.PR_TITLE }}>"
                    },
                    {
                        "title": "Run Link",
                        "value": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                ],
                "thumb_url": "https://raw.githubusercontent.com/zooniverse/Brand/master/style%20guide/logos/zooniverse-emblem/zooniverse-logo-teal.png",
                "footer": "<https://github.com/${{ github.repository }}|${{ github.repository }}> #${{ github.run_number }}",
                "footer_icon": "https://www.zooniverse.org/favicon.ico"
              }]
            }
